/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.Issues;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssuesRecord extends UpdatableRecordImpl<IssuesRecord> implements Record8<Integer, String, String, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 406139647;

    /**
     * Setter for <code>ISSUES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ISSUES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ISSUES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ISSUES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ISSUES.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ISSUES.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ISSUES.STATUS_ID</code>.
     */
    public void setStatusId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ISSUES.STATUS_ID</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ISSUES.ASSIGNEE_ID</code>.
     */
    public void setAssigneeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ISSUES.ASSIGNEE_ID</code>.
     */
    public Integer getAssigneeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ISSUES.PRIORITY</code>.
     */
    public void setPriority(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ISSUES.PRIORITY</code>.
     */
    public Integer getPriority() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ISSUES.TASK_ID</code>.
     */
    public void setTaskId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ISSUES.TASK_ID</code>.
     */
    public Integer getTaskId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ISSUES.PROJECT_ID</code>.
     */
    public void setProjectId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ISSUES.PROJECT_ID</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Issues.ISSUES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Issues.ISSUES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Issues.ISSUES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Issues.ISSUES.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Issues.ISSUES.ASSIGNEE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Issues.ISSUES.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Issues.ISSUES.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Issues.ISSUES.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAssigneeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value4(Integer value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value5(Integer value) {
        setAssigneeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value6(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value7(Integer value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord value8(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssuesRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IssuesRecord
     */
    public IssuesRecord() {
        super(Issues.ISSUES);
    }

    /**
     * Create a detached, initialised IssuesRecord
     */
    public IssuesRecord(Integer id, String name, String description, Integer statusId, Integer assigneeId, Integer priority, Integer taskId, Integer projectId) {
        super(Issues.ISSUES);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, statusId);
        set(4, assigneeId);
        set(5, priority);
        set(6, taskId);
        set(7, projectId);
    }
}
