/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.Sprints;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SprintsRecord extends UpdatableRecordImpl<SprintsRecord> implements Record5<Integer, String, Date, Date, Integer> {

    private static final long serialVersionUID = 1533501276;

    /**
     * Setter for <code>SPRINTS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SPRINTS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SPRINTS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SPRINTS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SPRINTS.START_DAY</code>.
     */
    public void setStartDay(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>SPRINTS.START_DAY</code>.
     */
    public Date getStartDay() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>SPRINTS.END_DAY</code>.
     */
    public void setEndDay(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>SPRINTS.END_DAY</code>.
     */
    public Date getEndDay() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>SPRINTS.PROJECT_ID</code>.
     */
    public void setProjectId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>SPRINTS.PROJECT_ID</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Date, Date, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Date, Date, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Sprints.SPRINTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Sprints.SPRINTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Sprints.SPRINTS.START_DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Sprints.SPRINTS.END_DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Sprints.SPRINTS.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getStartDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getEndDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord value3(Date value) {
        setStartDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord value4(Date value) {
        setEndDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord value5(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SprintsRecord values(Integer value1, String value2, Date value3, Date value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SprintsRecord
     */
    public SprintsRecord() {
        super(Sprints.SPRINTS);
    }

    /**
     * Create a detached, initialised SprintsRecord
     */
    public SprintsRecord(Integer id, String name, Date startDay, Date endDay, Integer projectId) {
        super(Sprints.SPRINTS);

        set(0, id);
        set(1, name);
        set(2, startDay);
        set(3, endDay);
        set(4, projectId);
    }
}
