/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.Tasks;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksRecord extends UpdatableRecordImpl<TasksRecord> implements Record6<Integer, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 159553207;

    /**
     * Setter for <code>TASKS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TASKS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TASKS.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>TASKS.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TASKS.ASSIGNEE</code>.
     */
    public void setAssignee(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>TASKS.ASSIGNEE</code>.
     */
    public Integer getAssignee() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>TASKS.TASK_STATUS</code>.
     */
    public void setTaskStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>TASKS.TASK_STATUS</code>.
     */
    public Integer getTaskStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TASKS.STORY_POINTS</code>.
     */
    public void setStoryPoints(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>TASKS.STORY_POINTS</code>.
     */
    public Integer getStoryPoints() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>TASKS.PROJECT_ID</code>.
     */
    public void setProjectId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>TASKS.PROJECT_ID</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tasks.TASKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tasks.TASKS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tasks.TASKS.ASSIGNEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tasks.TASKS.TASK_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Tasks.TASKS.STORY_POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Tasks.TASKS.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAssignee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTaskStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStoryPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value3(Integer value) {
        setAssignee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value4(Integer value) {
        setTaskStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value5(Integer value) {
        setStoryPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord value6(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TasksRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TasksRecord
     */
    public TasksRecord() {
        super(Tasks.TASKS);
    }

    /**
     * Create a detached, initialised TasksRecord
     */
    public TasksRecord(Integer id, String name, Integer assignee, Integer taskStatus, Integer storyPoints, Integer projectId) {
        super(Tasks.TASKS);

        set(0, id);
        set(1, name);
        set(2, assignee);
        set(3, taskStatus);
        set(4, storyPoints);
        set(5, projectId);
    }
}
