/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.UserStories;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStoriesRecord extends UpdatableRecordImpl<UserStoriesRecord> implements Record10<Integer, String, String, String, String, String, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1677763148;

    /**
     * Setter for <code>USER_STORIES.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER_STORIES.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER_STORIES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER_STORIES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>USER_STORIES.AS_A_STORY</code>.
     */
    public void setAsAStory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>USER_STORIES.AS_A_STORY</code>.
     */
    public String getAsAStory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>USER_STORIES.I_WANT_TO_STORY</code>.
     */
    public void setIWantToStory(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>USER_STORIES.I_WANT_TO_STORY</code>.
     */
    public String getIWantToStory() {
        return (String) get(3);
    }

    /**
     * Setter for <code>USER_STORIES.SO_THAT_STORY</code>.
     */
    public void setSoThatStory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>USER_STORIES.SO_THAT_STORY</code>.
     */
    public String getSoThatStory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>USER_STORIES.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>USER_STORIES.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>USER_STORIES.PRIORITY</code>.
     */
    public void setPriority(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>USER_STORIES.PRIORITY</code>.
     */
    public Integer getPriority() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>USER_STORIES.STORY_POINTS</code>.
     */
    public void setStoryPoints(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>USER_STORIES.STORY_POINTS</code>.
     */
    public Integer getStoryPoints() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>USER_STORIES.STATUS_ID</code>.
     */
    public void setStatusId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>USER_STORIES.STATUS_ID</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>USER_STORIES.PROJECT_ID</code>.
     */
    public void setProjectId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>USER_STORIES.PROJECT_ID</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, String, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserStories.USER_STORIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserStories.USER_STORIES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserStories.USER_STORIES.AS_A_STORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserStories.USER_STORIES.I_WANT_TO_STORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserStories.USER_STORIES.SO_THAT_STORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserStories.USER_STORIES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return UserStories.USER_STORIES.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return UserStories.USER_STORIES.STORY_POINTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return UserStories.USER_STORIES.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return UserStories.USER_STORIES.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAsAStory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIWantToStory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSoThatStory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStoryPoints();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value3(String value) {
        setAsAStory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value4(String value) {
        setIWantToStory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value5(String value) {
        setSoThatStory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value7(Integer value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value8(Integer value) {
        setStoryPoints(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value9(Integer value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord value10(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStoriesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserStoriesRecord
     */
    public UserStoriesRecord() {
        super(UserStories.USER_STORIES);
    }

    /**
     * Create a detached, initialised UserStoriesRecord
     */
    public UserStoriesRecord(Integer id, String name, String asAStory, String iWantToStory, String soThatStory, String description, Integer priority, Integer storyPoints, Integer statusId, Integer projectId) {
        super(UserStories.USER_STORIES);

        set(0, id);
        set(1, name);
        set(2, asAStory);
        set(3, iWantToStory);
        set(4, soThatStory);
        set(5, description);
        set(6, priority);
        set(7, storyPoints);
        set(8, statusId);
        set(9, projectId);
    }
}
