/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.UsersSettings;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersSettingsRecord extends UpdatableRecordImpl<UsersSettingsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1654822079;

    /**
     * Setter for <code>USERS_SETTINGS.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USERS_SETTINGS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USERS_SETTINGS.RECENT_PROJECT_ID</code>.
     */
    public void setRecentProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>USERS_SETTINGS.RECENT_PROJECT_ID</code>.
     */
    public Integer getRecentProjectId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UsersSettings.USERS_SETTINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UsersSettings.USERS_SETTINGS.RECENT_PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRecentProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSettingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSettingsRecord value2(Integer value) {
        setRecentProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSettingsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersSettingsRecord
     */
    public UsersSettingsRecord() {
        super(UsersSettings.USERS_SETTINGS);
    }

    /**
     * Create a detached, initialised UsersSettingsRecord
     */
    public UsersSettingsRecord(Integer id, Integer recentProjectId) {
        super(UsersSettings.USERS_SETTINGS);

        set(0, id);
        set(1, recentProjectId);
    }
}
