/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.UserRolesInProject;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRolesInProjectRecord extends UpdatableRecordImpl<UserRolesInProjectRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1230308516;

    /**
     * Setter for <code>USER_ROLES_IN_PROJECT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>USER_ROLES_IN_PROJECT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>USER_ROLES_IN_PROJECT.ROLE</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>USER_ROLES_IN_PROJECT.ROLE</code>.
     */
    public String getRole() {
        return (String) get(1);
    }

    /**
     * Setter for <code>USER_ROLES_IN_PROJECT.COLOR</code>.
     */
    public void setColor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>USER_ROLES_IN_PROJECT.COLOR</code>.
     */
    public String getColor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>USER_ROLES_IN_PROJECT.PRIVILIGES</code>.
     */
    public void setPriviliges(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>USER_ROLES_IN_PROJECT.PRIVILIGES</code>.
     */
    public Integer getPriviliges() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserRolesInProject.USER_ROLES_IN_PROJECT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserRolesInProject.USER_ROLES_IN_PROJECT.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserRolesInProject.USER_ROLES_IN_PROJECT.COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserRolesInProject.USER_ROLES_IN_PROJECT.PRIVILIGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPriviliges();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRolesInProjectRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRolesInProjectRecord value2(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRolesInProjectRecord value3(String value) {
        setColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRolesInProjectRecord value4(Integer value) {
        setPriviliges(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRolesInProjectRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRolesInProjectRecord
     */
    public UserRolesInProjectRecord() {
        super(UserRolesInProject.USER_ROLES_IN_PROJECT);
    }

    /**
     * Create a detached, initialised UserRolesInProjectRecord
     */
    public UserRolesInProjectRecord(Integer id, String role, String color, Integer priviliges) {
        super(UserRolesInProject.USER_ROLES_IN_PROJECT);

        set(0, id);
        set(1, role);
        set(2, color);
        set(3, priviliges);
    }
}
