/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Wojtek Stanisławski' at '19.11.16 15:04' with Gradle 3.2
 *
 * @author Wojtek Stanisławski, @date 19.11.16 15:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
