/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.pg.eti.kio.skroom.model.dba.DefaultSchema;
import pl.pg.eti.kio.skroom.model.dba.Keys;
import pl.pg.eti.kio.skroom.model.dba.tables.records.IssuesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Issues extends TableImpl<IssuesRecord> {

    private static final long serialVersionUID = -1304916161;

    /**
     * The reference instance of <code>ISSUES</code>
     */
    public static final Issues ISSUES = new Issues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IssuesRecord> getRecordType() {
        return IssuesRecord.class;
    }

    /**
     * The column <code>ISSUES.ID</code>.
     */
    public final TableField<IssuesRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ISSUES.NAME</code>.
     */
    public final TableField<IssuesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ISSUES.DESCRIPTION</code>.
     */
    public final TableField<IssuesRecord, String> DESCRIPTION = createField("DESCRIPTION", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>ISSUES.STATUS_ID</code>.
     */
    public final TableField<IssuesRecord, Integer> STATUS_ID = createField("STATUS_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ISSUES.ASSIGNEE_ID</code>.
     */
    public final TableField<IssuesRecord, Integer> ASSIGNEE_ID = createField("ASSIGNEE_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ISSUES.PRIORITY</code>.
     */
    public final TableField<IssuesRecord, Integer> PRIORITY = createField("PRIORITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ISSUES.TASK_ID</code>.
     */
    public final TableField<IssuesRecord, Integer> TASK_ID = createField("TASK_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>ISSUES.PROJECT_ID</code>.
     */
    public final TableField<IssuesRecord, Integer> PROJECT_ID = createField("PROJECT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>ISSUES</code> table reference
     */
    public Issues() {
        this("ISSUES", null);
    }

    /**
     * Create an aliased <code>ISSUES</code> table reference
     */
    public Issues(String alias) {
        this(alias, ISSUES);
    }

    private Issues(String alias, Table<IssuesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Issues(String alias, Table<IssuesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IssuesRecord> getPrimaryKey() {
        return Keys.PK_ISSUES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IssuesRecord>> getKeys() {
        return Arrays.<UniqueKey<IssuesRecord>>asList(Keys.PK_ISSUES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<IssuesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<IssuesRecord, ?>>asList(Keys.FK_ISSUES_TASK_STATUSES_1, Keys.FK_ISSUES_USERS_1, Keys.FK_ISSUES_TASKS_1, Keys.FK_ISSUES_PROJECTS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Issues as(String alias) {
        return new Issues(alias, this);
    }

    /**
     * Rename this table
     */
    public Issues rename(String name) {
        return new Issues(name, null);
    }
}
