/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.pg.eti.kio.skroom.model.dba.DefaultSchema;
import pl.pg.eti.kio.skroom.model.dba.Keys;
import pl.pg.eti.kio.skroom.model.dba.tables.records.UsersSettingsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersSettings extends TableImpl<UsersSettingsRecord> {

    private static final long serialVersionUID = 377052404;

    /**
     * The reference instance of <code>USERS_SETTINGS</code>
     */
    public static final UsersSettings USERS_SETTINGS = new UsersSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersSettingsRecord> getRecordType() {
        return UsersSettingsRecord.class;
    }

    /**
     * The column <code>USERS_SETTINGS.ID</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERS_SETTINGS.USER_ID</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERS_SETTINGS.RECENT_PROJECT_ID</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> RECENT_PROJECT_ID = createField("RECENT_PROJECT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERS_SETTINGS.USER_STORIES_PER_PAGE</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> USER_STORIES_PER_PAGE = createField("USER_STORIES_PER_PAGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERS_SETTINGS.TASKS_PER_PAGE</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> TASKS_PER_PAGE = createField("TASKS_PER_PAGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERS_SETTINGS.USERS_PER_PAGE</code>.
     */
    public final TableField<UsersSettingsRecord, Integer> USERS_PER_PAGE = createField("USERS_PER_PAGE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>USERS_SETTINGS</code> table reference
     */
    public UsersSettings() {
        this("USERS_SETTINGS", null);
    }

    /**
     * Create an aliased <code>USERS_SETTINGS</code> table reference
     */
    public UsersSettings(String alias) {
        this(alias, USERS_SETTINGS);
    }

    private UsersSettings(String alias, Table<UsersSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersSettings(String alias, Table<UsersSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UsersSettingsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USERS_SETTINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsersSettingsRecord> getPrimaryKey() {
        return Keys.PK_USERS_SETTINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsersSettingsRecord>> getKeys() {
        return Arrays.<UniqueKey<UsersSettingsRecord>>asList(Keys.PK_USERS_SETTINGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UsersSettingsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UsersSettingsRecord, ?>>asList(Keys.FK_USERS_SETTINGS_USERS_1, Keys.FK_USERS_SETTINGS_PROJECTS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersSettings as(String alias) {
        return new UsersSettings(alias, this);
    }

    /**
     * Rename this table
     */
    public UsersSettings rename(String name) {
        return new UsersSettings(name, null);
    }
}
