DROP TABLE TASKS;

DROP TABLE USERS_SECURITY;
DROP TABLE USERS_SETTINGS;
DROP TABLE USER_ROLES_IN_PROJECT;
DROP TABLE USERS_PROJECTS;
DROP TABLE USERS;

DROP TABLE USER_STORIES;
DROP TABLE USER_STORY_STATUS;

DROP TABLE SPRINTS;
DROP TABLE PROJECTS;
