DROP TABLE TASKS;

CREATE TABLE TASKS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT,
	ASSIGNEE INTEGER,
	TASK_STATUS INTEGER,
	STORY_POINTS INTEGER,
	PROJECT_ID INTEGER,
	FOREIGN KEY(ASSIGNEE) REFERENCES USERS(ID),
	FOREIGN KEY(PROJECT_ID) REFERENCES PROJECTS(ID)
);
