CREATE TABLE USER_STORIES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT,
	PRIORITY INTEGER,
	STORY_POINTS INTEGER,
	STATUS INTEGER,
	PROJECT_ID INTEGER,
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
);
