/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pl.pg.eti.kio.skroom.model.dba.tables.Projects;
import pl.pg.eti.kio.skroom.model.dba.tables.SqliteSequence;
import pl.pg.eti.kio.skroom.model.dba.tables.Tasks;
import pl.pg.eti.kio.skroom.model.dba.tables.UserRolesInProject;
import pl.pg.eti.kio.skroom.model.dba.tables.UserStories;
import pl.pg.eti.kio.skroom.model.dba.tables.Users;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersProjects;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersSecurity;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersSettings;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1268727225;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>PROJECTS</code>.
     */
    public final Projects PROJECTS = pl.pg.eti.kio.skroom.model.dba.tables.Projects.PROJECTS;

    /**
     * The table <code>TASKS</code>.
     */
    public final Tasks TASKS = pl.pg.eti.kio.skroom.model.dba.tables.Tasks.TASKS;

    /**
     * The table <code>USERS</code>.
     */
    public final Users USERS = pl.pg.eti.kio.skroom.model.dba.tables.Users.USERS;

    /**
     * The table <code>USERS_PROJECTS</code>.
     */
    public final UsersProjects USERS_PROJECTS = pl.pg.eti.kio.skroom.model.dba.tables.UsersProjects.USERS_PROJECTS;

    /**
     * The table <code>USERS_SECURITY</code>.
     */
    public final UsersSecurity USERS_SECURITY = pl.pg.eti.kio.skroom.model.dba.tables.UsersSecurity.USERS_SECURITY;

    /**
     * The table <code>USERS_SETTINGS</code>.
     */
    public final UsersSettings USERS_SETTINGS = pl.pg.eti.kio.skroom.model.dba.tables.UsersSettings.USERS_SETTINGS;

    /**
     * The table <code>USER_ROLES_IN_PROJECT</code>.
     */
    public final UserRolesInProject USER_ROLES_IN_PROJECT = pl.pg.eti.kio.skroom.model.dba.tables.UserRolesInProject.USER_ROLES_IN_PROJECT;

    /**
     * The table <code>USER_STORIES</code>.
     */
    public final UserStories USER_STORIES = pl.pg.eti.kio.skroom.model.dba.tables.UserStories.USER_STORIES;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = pl.pg.eti.kio.skroom.model.dba.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Projects.PROJECTS,
            Tasks.TASKS,
            Users.USERS,
            UsersProjects.USERS_PROJECTS,
            UsersSecurity.USERS_SECURITY,
            UsersSettings.USERS_SETTINGS,
            UserRolesInProject.USER_ROLES_IN_PROJECT,
            UserStories.USER_STORIES,
            SqliteSequence.SQLITE_SEQUENCE);
    }
}
