/**
 * This class is generated by jOOQ
 */
package pl.pg.eti.kio.skroom.model.dba;


import javax.annotation.Generated;

import pl.pg.eti.kio.skroom.model.dba.tables.Projects;
import pl.pg.eti.kio.skroom.model.dba.tables.SqliteSequence;
import pl.pg.eti.kio.skroom.model.dba.tables.Tasks;
import pl.pg.eti.kio.skroom.model.dba.tables.UserRolesInProject;
import pl.pg.eti.kio.skroom.model.dba.tables.UserStories;
import pl.pg.eti.kio.skroom.model.dba.tables.Users;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersProjects;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersSecurity;
import pl.pg.eti.kio.skroom.model.dba.tables.UsersSettings;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PROJECTS</code>.
     */
    public static final Projects PROJECTS = pl.pg.eti.kio.skroom.model.dba.tables.Projects.PROJECTS;

    /**
     * The table <code>TASKS</code>.
     */
    public static final Tasks TASKS = pl.pg.eti.kio.skroom.model.dba.tables.Tasks.TASKS;

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = pl.pg.eti.kio.skroom.model.dba.tables.Users.USERS;

    /**
     * The table <code>USERS_PROJECTS</code>.
     */
    public static final UsersProjects USERS_PROJECTS = pl.pg.eti.kio.skroom.model.dba.tables.UsersProjects.USERS_PROJECTS;

    /**
     * The table <code>USERS_SECURITY</code>.
     */
    public static final UsersSecurity USERS_SECURITY = pl.pg.eti.kio.skroom.model.dba.tables.UsersSecurity.USERS_SECURITY;

    /**
     * The table <code>USERS_SETTINGS</code>.
     */
    public static final UsersSettings USERS_SETTINGS = pl.pg.eti.kio.skroom.model.dba.tables.UsersSettings.USERS_SETTINGS;

    /**
     * The table <code>USER_ROLES_IN_PROJECT</code>.
     */
    public static final UserRolesInProject USER_ROLES_IN_PROJECT = pl.pg.eti.kio.skroom.model.dba.tables.UserRolesInProject.USER_ROLES_IN_PROJECT;

    /**
     * The table <code>USER_STORIES</code>.
     */
    public static final UserStories USER_STORIES = pl.pg.eti.kio.skroom.model.dba.tables.UserStories.USER_STORIES;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = pl.pg.eti.kio.skroom.model.dba.tables.SqliteSequence.SQLITE_SEQUENCE;
}
