print("Starting Skroom Development Build 0.1.7 server...")
print("Reading WAR file..")
print("Fetching resources..")
print("Create database..")
print("Fetching resources..")
print("Server successfully started.")
print("Please log in into http://localhost:8080/skroom")
print("Default admin authorisation data")
print("Username: admin")
print("Password: admin")
print("Press Ctrl+C to shut down server")
print("Server is running.")
input('')