/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Wojtek Stanisławski' at '11.01.17 20:58' with Gradle 3.0
 *
 * @author Wojtek Stanisławski, @date 11.01.17 20:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
